//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ID { get; set; }
        public string Name_ar { get; set; }
        public string Name_en { get; set; }
        public Nullable<long> Cat_ID { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public byte[] Prod_Pic { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Created_By { get; set; }
        public string Description { get; set; }
        public Nullable<double> Tax_Percentage { get; set; }
    }
}
