//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Has_Role
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Role_Start_Time { get; set; }
        public Nullable<System.DateTime> Role_End_Time { get; set; }
        public Nullable<long> Role_ID { get; set; }
        public Nullable<long> User_Account_ID { get; set; }
    }
}
