//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public long ID { get; set; }
        public string Name_ar { get; set; }
        public string Name_en { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
